export default [
  { id: 1, value: '1', label: 'HR/Office/Legal' },
  { id: 2, value: '2', label: 'Audio' },
  { id: 3, value: '3', label: 'Sales/Marketing' },
  { id: 4, value: '4', label: 'Management' },
  { id: 5, value: '5', label: 'Community Management' },
  { id: 7, value: '7', label: 'Design/Product' },
  { id: 8, value: '8', label: 'Academia' },
  { id: 9, value: '9', label: 'Finance' },
  { id: 11, value: '11', label: 'Engineering' },
  { id: 12, value: '12', label: 'QA/Localization' },
  { id: 14, value: '14', label: 'Not Listed' },
  { id: 16, value: '16', label: 'Production' },
  { id: 17, value: '17', label: 'Product/Analyst' },
  { id: 23, value: '23', label: 'Art/Animation' },
  { id: 24, value: '24', label: 'Acting/Writing' },
  { id: 25, value: '25', label: 'Publishing' },
  { id: 26, value: '26', label: 'eSports' },
  { id: 27, value: '27', label: 'Student' },
];
